<?php
$naam_app = $_POST['naam_app'];
$url = $_POST['url'];
$google = $_POST['showthis'];
$ios = $_POST['ios'];
$android = $_POST['android'];
$windows = $_POST['windows'];
$support = $_POST["support_email"];
$weergave_naam = $_POST["weergave_naam"];
$email_onthouden = $_POST["email_onthouden"];
$wachtwoord_onthouden = $_POST["wachtwoord_onthouden"];
$apparaat_activatie = $_POST["apparaat_activatie"];
$beveiliging = $_POST["amountInput"];
$inc1 = $_POST["incrowds_1"];
$inc2 = $_POST["incrowds_2"];
$inc3 = $_POST["incrowds_3"];
$inc4 = $_POST["incrowds_4"];
$inc5 = $_POST["incrowds_5"];
$ong_berichten = $_POST["ongelezen_berichten"];
$gebruiker_1 = $_POST["gebruiker_1"];
$email_1 = $_POST["email_1"];
$gebruiker_2 = $_POST["gebruiker_2"];
$email_2 = $_POST["email_2"];
$gebruiker_3 = $_POST["gebruiker_3"];
$email_3 = $_POST["email_3"];
$bijlage_1 = $_POST["bijlage_1"];
$bijlage_2 = $_POST["bijlage_2"];
$bijlage_3 = $_POST["bijlage_3"];




require("fpdf.php");
$pdf = new FPDF('P', 'mm', 'A4');
$pdf->addPage();
$pdf->setFont("Arial", "B", 16);
$pdf->SetWidths(array(30,50,30,40));
$pdf->Image('fpdf/incrowd2.png',15,5,200,43.3);
$pdf->Cell(0, 30, "",1,1,C);
$pdf->Cell(0, 10, "INCROWD INTAKEFORMULIER",1,1,C);
$pdf->Cell(0, 10, "Naam van de app: {$naam_app}", 1,1);
$pdf->Cell(0, 10, "URL van de app: http://{$url}.incrowdpro.nl/", 1,1);
$pdf->Cell(0, 10, "Google Analytics account: {$showthis}", 1,1);
$pdf->Cell(0, 10, "iOS app: {$ios}", 1,1);
$pdf->Cell(0, 10, "Android app: {$android}", 1,1);
$pdf->Cell(0, 10, "Windows app: {$windows}", 1,1);
$pdf->Cell(0, 10, "Support Email: {$support}", 1,1);
$pdf->Cell(0, 10, "Weergavenaam: {$weergave_naam}", 1,1);
$pdf->Cell(0, 10, "Email onthouden: {$email_onthouden}", 1,1);
$pdf->Cell(0, 10, "Wachtwoord onthouden: {$wachtwoord_onthouden}", 1,1);
$pdf->Cell(0, 10, "Apparaat activatie: {$apparaat_activatie}", 1,1);
$pdf->Cell(0, 10, "Beveiliging: {$beveiliging} Minuten", 1,1);
$pdf->Cell(0, 10, "Incrowd 1: {$inc1}", 1,1);
$pdf->Cell(0, 10, "Incrowd 2: {$inc2}", 1,1);
$pdf->Cell(0, 10, "Incrowd 3: {$inc3}", 1,1);
$pdf->Cell(0, 10, "Incrowd 4: {$inc4}", 1,1);
$pdf->Cell(0, 10, "Incrowd 5: {$inc5}", 1,1);
$pdf->Cell(0, 10, "Ongelezen berichten-badge: {$ong_berichten}", 1,1);
$pdf->Cell(0, 10, "Gebruiker 1: {$gebruiker_1}", 1,1);
$pdf->Cell(0, 10, "Email 1: {$email_1}", 1,1);
$pdf->Cell(0, 10, "Gebruiker 2: {$gebruiker_2}", 1,1);
$pdf->Cell(0, 10, "Email 2: {$email_2}", 1,1);
$pdf->Cell(0, 10, "Gebruiker 3: {$gebruiker_3}", 1,1);
$pdf->Cell(0, 10, "Email 3: {$email_3}", 1,1);
$pdf->Cell(0, 10, "Bijlage 1: {$bijlage_1}", 1,1);
$pdf->Cell(0, 10, "Bijlage 2: {$bijlage_2}", 1,1);
$pdf->Cell(0, 10, "Bijlage 3: {$bijlage_3}", 1,1);
ob_end_clean();
$pdf->output();
?>
